### PR TITLE
remove loop if the body got emptied by assert_if

### PR DESCRIPTION
**Pull request by yamaguchi1024**

### CODE REVIEW

**Review by alexreinking — APPROVED** [review]
It would be nice to have some standard logic that enforced this.

**Comment by yamaguchi1024** [comment]
@alexreinking yeah, I even think this should be part of original LoopIR_Rewrite class

**Comment by gilbo** [comment]
It would be reasonable to subclass Rewrite for scheduling rewrite passes specifically. Doing so could help standardize passes and give a place to install helper functionality

**Comment by yamaguchi1024** [comment]
Yeah that sounds good

**Pull request merged**
