### PR TITLE
update some code in /apps/gemini/src/platform

### PR DESCRIPTION
**Pull request by xiuhu17**

### CODE REVIEW

**Comment by yamaguchi1024** [comment]
Hi @xiuhu17 ! Thanks for the PR. Could you explain why you had to change the Gemmini malloc code? Was it incorrect in some cases? Could you provide a reproducer?

**Comment by xiuhu17** [comment]
Hi @yamaguchi1024 , the reason I change it because the original code looks like: 
```
uint32_t loc = 0;
  if (i > 0) {
    loc = ACC_BLOCKS[i - 1].loc + ACC_BLOCKS[i - 1].size;
  }
  ACC_BLOCKS[i].size = size;
  ACC_BLOCKS[i].loc = 0;
```

The `loc` seems to be useless, and the return value will always be `0x80000000`.

**Comment by yamaguchi1024** [comment]
Sorry for dropping the ball on this! The Gemmini malloc files are a bit stale honestly, and I don't think there's any test case that executes this either. I'm really curious how you found this bug. Were you trying to repurpose this code for some other memory allocation?

**Comment by xiuhu17** [comment]
> Sorry for dropping the ball on this! The Gemmini malloc files are a bit stale honestly, and I don't think there's any test case that executes this either. I'm really curious how you found this bug. Were you trying to repurpose this code for some other memory allocation?

Yeh, I previously was trying to figure out the allocation logic used by EXO, I read the code and found that issue. :)

**Review by yamaguchi1024 — APPROVED** [review]

**Comment by yamaguchi1024** [comment]
@xiuhu17 great, thanks for the contribution!

**Pull request merged**
