### PR TITLE
Add restrict qualifier to pointers at codegen

### PR DESCRIPTION
**Pull request by SamirDroubi**

### CODE REVIEW

**Comment by yamaguchi1024** [comment]
Is this really safe? IIUC there's some code (like syr) that actually aliases the call to Exo kernels. Also, did you see any speedup from changing this?

**Comment by skeqiqevian** [comment]
What was the reason we needed aliasing for `syr` again? Is it so that you can perform `stage_mem` correctly on only one of the vectors without impacting the other?

**Review by yamaguchi1024 — APPROVED** [review]
LGTM, but you should remove the aliasing kernel call after the stage_mem PR gets mergeed

**Comment by yamaguchi1024** [comment]
Closing due to inactivity

**Pull request closed without merging**
